CONTRIBUTING.md
README.md

Initial commits for README and CONTRIBUTING files. Also incorporates the all-contributors standards. 
Currently, CONTRIBUTING points to the [brainhack code of conduct](http://www.brainhack.org/code-of-conduct.html), but this can be updated after the resolution of #9.

Add README, CONTRIBUTING

---

index.html

I find current about a bit too non-specific, so shuffled pieces around to provide first the About (blurb) and then list of benefits also adding id= for software paragraph so a dedicated url could be used where needed to point to software pieces.
Also, I would have increased size for the `ul.li` items but didn't want to disturb it all in one shot ;)  Ideally also if someone could word benefits more concisely with `<strong>`ifying main benefits keywords in that rewording -- could be easier to digest and deliver the main points.

ENH: Split About block into About and Benefits

---

index.html

at the moment online version on readthedocs is not linked to, although it is much more accessible.

provide link to online readthedocs specifications

---

index.html

External links from [https://bids.neuroimaging.io](https://bids.neuroimaging.io) (e.g. to the starter kit) are not active if the Google Tag Manager code cannot be loaded.  Following the guidelines at [https://hacks.mozilla.org/2016/01/google-analytics-privacy-and-event-tracking/](https://hacks.mozilla.org/2016/01/google-analytics-privacy-and-event-tracking/) this commit adds a fallback to the trackOutboundLink function allowing tracked links to be followed in the event that the gtag object is not available e.g. due to network errors or client tracking protection.
TODO: confirm that tracking still functions with the fallback in place.

Add fallback to trackOutboundLink

---

index.html

closes #50 
- ~~Feedback form re-enabled~~ see #52 
For now, I only fixed one of the issues. I don't know which alternative link I should use for the INCF task force link.
And I am waiting for information from @franklin-feingold regarding the feedback form.

fix incf link

---

index.html

related to #50 #51 #52 
BTW, I was not successful finding the broken INCF NI Task force link.
Perhaps we can for now just link to this one, from the wayback-machine:
https://web.archive.org/web/20170813183704/http://wiki.incf.org/mediawiki/index.php/Neuroimaging_Task_Force

fix INCF NI taskforce link

---

_data/navigation.yaml

closes #89 
This fixes our circleci build and should not affect the "in production" website.
You can see for yourself by trying out the following two links. Both work and resolve to the same thing:
- https://bids.neuroimaging.io/index
- https://bids.neuroimaging.io/index.html

append .html to urls in nav

---

_pages/index.md
_posts/2020-03-12-Steering-Group-executive-summary,-action-items,-and-minutes.md

This PR addresses a request to distinguish between the BIDS specification and its ecosystem @franklin-feingold 
what I did:
- Put each sentence on its own line ... no line breaks within a sentence --> This will make inspection of the diff much easier in the future
- added a short section stating that we are an open community
- added section to distinguish BIDS specification vs. ecosystem
- put link info from bottom into its own section and turn it into list

[DOC] add community and ecosystem sections

---

.circleci/config.yml
.remarkrc
_pages/code_of_conduct.md
_pages/governance.md
_posts/2020-01-02-announcement-community-forum-events.md
_posts/2020-03-12-Steering-Group-executive-summary,-action-items,-and-minutes.md
_posts/2020-03-23-Steering-Group-executive-summary,-action-items,-and-minutes.md
npm-requirements.txt

closes #82 
I suggest that we use a very soft Markdown linter preset like [remark-preset-lint-recommended](https://github.com/remarkjs/remark-lint/tree/master/packages/remark-preset-lint-recommended), which will ensure that we don't have syntax errors ... yet we can stay a bit more flexible with how we format things (for now).

CI: add linter

---

.circleci/artifact_path
.circleci/config.yml
.github/workflows/artifacts_redirector.yml
README.md

fixes #105 
This PR:
- adds GEM caching for circleci builds, resulting in faster builds
- fixes the artifact redirection GitHub action by implementing it as a proper GitHub Action
- as a result, the little link listed under "checks" in each PR will work again, and the rendering of the circleci website artifact will be correct
The effect of the GitHub Action will only be in effect after merging this PR. But I tested this extensively on https://github.com/sappelhoff/bids-website
try yourself by clicking on the CIs of the most recent build. See screenshot. Navigate to my fork and click on the colorful round button next to the latest commit:

FIX: use artifact redir as GH action

---

_pages/specification.md

Revised the one-sentence Specification webpage to refer to both the online and PDF versions.  There are of course many different ways to phrase/cast this... happy to have suggestions on how to improve the edit.
This addresses https://github.com/bids-standard/bids-specification/issues/135#issuecomment-614659807

Revise Specification page to point to both online and PDF versions

---

_pages/governance.md

updated link to the list of BEPs, it is here on the bids website rather than in the bids-specification

Fix link in governance.md

---

_posts/2020-06-24-Join-the-BIDS-community-on-the-BrainHack-Mattermost.md

This PR adds a post announcing our decision to use the BrainHack Mattermost as our instant messaging solution for BIDS. I wanted to take advantage of OHBM for announcing this decision. I listed an initial set of BIDS channels that are currently live. Once I have the grander BIDS Organization - this list will be updated.
Note: There are several channels that are not active or OHBM hackathon projects - I have omitted them.
Note2: Our remark does not like emails. When there is an angle bracket we get this error message `All automatic links must start with a protocol`. When there I use a literal url we get this error message `Don’t use literal URLs without angle brackets`. Separate issue can be to ease our linter, but I think this is an edge case that shouldn't necessarily move the needle …

Mattermost announcement

---

_pages/get_involved.md

Adding this additional header will make it more clear these BEPs have been completed when skimming the webpage

Add `Completed BEP` table section header

---

_sass/custom.scss

Changing the base font size to 16px to improve readability and, therefore, accessibility (a11y).
Related to GH-141, GH-68.

Improve a11y with larger base font size

---

_sass/custom.scss

Related to GH-141, GH-68.
Link color had to be adjusted because links became undifferentiable from ordinary text with the increased brightness.
I don't have great eyesight and these changes, together with #158, make reading through the website **so** much more pleasant for me, without having to manually crank up the zoom level and contrast.
Happy to discuss the color scheme.

Slightly brighter font & changed link color to improve a11y

---

_sass/custom.scss

Obviously this only produces acceptable results in combination with hyphenation, so enable this too.

Justify text in paragraphs

---

_posts/2020-11-02-BIDS-ASL-community-review.md

PR initializes the beginning of the BIDS-ASL community review running through November 13

BIDS-ASL community review post

---

_posts/2021-01-11-BIDS-PET-community-review.md

PR initializes the beginning of the BIDS-PET community review running through January 22. 
[1/8 note: Draft due to verbiage regarding PET additions to the specification is being drafted]

Add BIDS-PET community review

---

_posts/2021-01-11-BIDS-PET-community-review.md

We have pushed back the PET community review close date to Feb. 12. This PR adds this update to the existing news item

Update PET community review close date

---

_pages/benefits.md

Clinica provides BIDS [converters](https://aramislab.paris.inria.fr/clinica/docs/public/latest/#dataset-converters-clinica-convert) for several publicly available neuroimaging datasets as well as BIDS dataset management [utilities](https://aramislab.paris.inria.fr/clinica/docs/public/latest/IO/#data-handling-tools).

Add Clinica to the list of available BIDS converters

---

_data/maintainers.yml
_data/steering.yml
_includes/members_table.html
_pages/governance.md

fixes #167 
- "layout" was mostly adapted from the one autogenerated by the all contributors bot
- also added the beginning of a list of which maintainers is "responsible" for what and who to contact.
For the email addresses, I am not using our personal addresses but using the "alias" feature of gmail on the bids maintainers gmail.
Might make sense to set up filter on the gmail side to not miss those.
```
- bids-website and domain ( [Franklin Feingold](mailto:bids.maintenance+website@gmail.com) )
- twitter account ( [Franklin Feingold](mailto:bids.maintenance+twitter@gmail.com) )
- youtube account ( [Rémi Gau](mailto:bids.maintenance+youtube@gmail.com) )
```

Add list of steering group and maintainers members

---

_posts/2021-06-15-BIDS-Town-Hall-2021.md

pull request intends to add our BIDS Town Hall 2021 announcement into our blog section. We will be using Eventbrite for managing the distribution of the zoom link - this is scheduled to happen 2 hours before the event 
edit: linkchecker failed on several files not associated with this PR (appears to be addressed in https://github.com/bids-standard/bids-website/pull/189) - perhaps this PR can get in due to its time sensitivity

Town Hall 2021 announcement

---

_data/navigation.yaml
_pages/get_started.md

address two low effort but nice to have points from #200 
- "THE SPECIFICATION" --> "SPECIFICATION" in navbar (shorter, and equally nice)
- "GETTING STARTED" --> GET STARTED in navbar (and file name; it's shorter, and parallel with GET INVOLVED)
The remaining points from #200 might require more discussion

rename sections for consistency/style

---

_config.yml
_includes/steering_group_election_section.html
_layouts/default.html
_sass/custom.scss

This adds a "steering group election" banner below the nav bar of all pages.
- it can be toggled by setting `election_banner` to `true` or `false` in `_config.yml`
- the content can be updated in  `_includes/steering_group_election_section.html`

[ENH] Add election banner

---

_data/maintainers.yml
_data/past_steering.yml
_data/steering.yml
_includes/members_table.html
_pages/governance.md

closes #216 
- adds @arokem to the steering group
- moves @KirstieJane to the newly created section for past members of the steering
- adds @ericearl to the maintainers
- uses proper jekyll - liquid syntax to create the generate the tables

[ENH] update steering committee

---

_data/converters.yml

@sappelhoff 
SAMRI also includes plenty of analysis and preprocessing functions for BIDS archives, and we already have [an article which documents and benchmarks the registration workflow](https://www.sciencedirect.com/science/article/pii/S1053811921006625).
Is there any other place on the website where I could add this?

Extra SAMRI information

---

_pages/get_started.md
_pages/governance.md
_redirects/starter-kit.md

minor details pointed out by https://github.com/bids-standard/bids-starter-kit/issues/253

[FIX] change link for starter kit from wiki or repo to book

---

_bep_collection/bep016.md

This is currently redirecting to an older Google doc that states that the BEP has been merged together with the common derivatives, but work still continues in this GitHub repository.

Redirect to new BEP16 repository

---

_data/maintainers.yml
_data/past_maintainers.yml
_pages/governance.md
_posts/2020-12-03-Steering-Group-executive-summary,-action-items,-and-minutes.md
_posts/2021-01-14-Steering-Group-executive-summary,-action-items,-and-minutes.md

related to doc updates in the spec as well:
- https://github.com/bids-standard/bids-specification/pull/1168
The doc also contains the following:
```
If you need to contact the maintainers on a specific topic you can use the following emails:
- bids-website and domain ( [Franklin Feingold](mailto:bids.maintenance+website@gmail.com) )
- twitter account ( [Franklin Feingold](mailto:bids.maintenance+twitter@gmail.com) )
- youtube account ( [Rémi Gau](mailto:bids.maintenance+youtube@gmail.com) )
```
How should we update this? cc @franklin-feingold 
EDIT: I just put my name in there for now.

General doc updates

---

_data/navigation.yaml
_includes/navbar.html
_layouts/default.html
_layouts/index.html
_sass/jekyll-theme-cayman.scss

Closes #93
https://mycyberuniverse.com/jekyll-bootstrap-dynamic-navigation-highlighting-active-element.html
also makes page content wider: gives better render of the converter tables

add dropdown possibility to navbar

---

_data/MEEG_converters.yml
_data/converters.yml
_data/from_BIDS_converters.yml
_data/other_converters.yml
_data/physio_converters.yml
_includes/beps_table.html
_includes/converters_table.html
_sass/custom.scss

[ENH] create lists for language, input type, data type for converters tables

---

_pages/governance.md
_posts/2022-11-07-BIDS-Steering-Group-Election-2022.md

noticed that we hadn't posted about the steering group election here.
I made a post and dated it back ... I think that's good for consistency reasons as we have posts for other elections that happened.
text simply copied from the [original announcement on the mailing list](https://groups.google.com/g/bids-discussion/c/kJ6DiA1uJ7Q)

late, dated back: add post on steering group elections

---

_data/physio_converters.yml

Since release 2.8, phys2bids supports GE data.

Update phys2bids supported input

---

_bep_collection/bep038.md
_data/beps.yml

This PR and the included commit are intended to make the Atlas BEP an official BEP by assigning it a number and subsequently sharing it with the wider community to follow the BEP development guidelines.

Proposal to make Atlas BEP an official BEP

---

_data/maintainers.yml

Will update https://bids.neuroimaging.io/governance.html#bids-maintainers-group.

Add Christine Rogers to maintainers list

---

_bep_collection/bep028.md

This reverts commit 5332c88315240d8b8a0c234aa57b8adffa042f11.
Following advise from @cmaumet , I have closed https://github.com/bids-standard/bids-specification/pull/487 since it got outdated and did not reflect the state of work, thus leading to confusion etc.

Revert "update bep028 link" to point back to google doc 

---

_data/physio_converters.yml

add bidsphysio to list of converters

---

_data/beps.yml
_data/beps_other.yml
_includes/beps_others_table.html
_pages/get_involved.md

- closes #323
- closes #328 
- marks BEP002 as completed moved with the "other 'completed'" BEPs with a link to the current bids stats model spec
- uses yml and jekyll "liquid magic" to render the table

move bep 02 and 19 to "completed"

---

_pages/governance.md

These changes were adopted by the BIDS community in the 2023 election.

Define active contributors and update voting procedure

---

_data/converters.yml

This PR adds [ezBIDS](https://github.com/brainlife/ezbids) to the list of currently available [BIDS converters](https://bids.neuroimaging.io/benefits) on the BIDS website.

[ENH] add ezBIDS to list of BIDS converters

---

_data/tools.yml

- bids stat model validator
- HED tools
- neurobagel tools
- file mapper

[ENH] add several tools

---

_pages/governance.md

ATM most of the changes might be changes to the schema, not as much to markdown text files. In the future we might acquire some other features (e.g. workflow figures etc) which would also need to be changed. Overall I think we should strive to remove as much of technical aspects from governance principles as possible -- they should be outlined in other documents, such as https://github.com/bids-standard/bids-extensions etc

Remove (now outdated/incomplete) going from Google doc to markdown file

---

_posts/2023-07-27-Steering-Group-minutes.md

The CI report highlighted broken links on the website. This commit addresses these issues by updating the URL to valid links. 
Issue fix #385

Fix the broken link reported by CI

---

data/beps.yml
data/beps_completed.yml
data/beps_other.yml
templates/beps_table_md.jinja

- Cleaned up BEPs links to not redirect.
- Made all external links in new tab.
- Adjusted beps table jinja file to take link from yaml file

BEPs redirect cleanup

---

data/beps_completed.yml
docs/bep/index.md

- getting involved text organized more easily readable
- edited superfluous info from completed beps yaml. (outcome is evident from BEP02 link and outcome field isn't needed for completed BEPs)

getting involved and completed bep yaml

---

data/tools/tools.yml

[ENH] add bids2table and ancpbids

---

data/tools/tools.yml
docs/tools/index.md
docs/tools/others.md
macros/macros.py
templates/tools_table_md.jinja

- closes #450 
- closes #447 
- add last commit badge to the table
- fix missing links to repo, documentation for several tools
- link in table should now be url if specified otherwise documentation, otherwise repo
- try to sort the tools "alphabetically" in the yml

[ENH] split tool tables by category

---

docs/extensions/general-guidelines.md

Addresses issue #470 
As mentioned in the issue, happy to make this a hard requirement but right now author is under the impression that the BEP process needs to be amended to do so.
Feel free to commit directly and merge if the author is wrong on this or tag him for a review.

[ENH] Require source to target data in bep guidelines

---

docs/tools/bids-apps.md
docs/tools/converters/index.md
docs/tools/converters/meeg.md
docs/tools/converters/mri-pet.md
docs/tools/converters/others.md
docs/tools/converters/physio.md
docs/tools/index.md

added intro and summaries per the 3rd milestone item. 
This PR closes #495

summaries and intros - tools section

---

docs/getting_started/folders_and_files/index.md
docs/getting_started/resources/index.md
docs/getting_started/resources/talks.md
docs/getting_started/tutorials/conversion/index.md
docs/getting_started/tutorials/index.md

Finished up all to do items on the 3rd eval milestone. 
This closes #494

[ENH] summaries and intros - getting started section

---

docs/getting_started/bids_apps/tutorial.md

[docker2singularity](https://hub.docker.com/r/singularityware/docker2singularity) appears to be no longer updated due to the fact that modern Apptainer (and later versions of singularity) support OCI (spec used by docker) natively.

Replace docker2singularity with singularity native

---

data/tools/tools.yml

see https://github.com/bids-standard/awesome-bids/pull/52
copy from there:
I would like to add https://mne.tools/mne-bids-pipeline to the list. For me the project was not easily findable, even though I already tinkered with MNE and BIDS for a few days. Including it here might make it more findable.
```
MNE-BIDS-Pipeline is a full-flegded processing pipeline for your MEG and EEG data.
It operates on data stored according to the [Brain Imaging Data Structure (BIDS)](https://bids.neuroimaging.io/).
Under the hood, it uses [MNE-Python](https://mne.tools/).
```

[ENH] Add mne-bids-pipeline

---

docs/blog/posts/2023-02-09-steering-group-minutes.md
docs/blog/posts/2023-05-25-steering-group-minutes.md
docs/blog/posts/community-review-pet.md
docs/collaboration/governance.md
docs/faq/general.md
docs/standards/schema/index.md

Links were broken by repo migration.

Move links from bids-validator to legacy-validator

---

docs/blog/posts/bids-validator-2.0.md

[Rendered post](https://bids-website--575.org.readthedocs.build/en/575/blog/2024/11/13/bids-validator-2.html)

BLOG: Add bids-validator 2.0 announcement

---

docs/index.md

This has been bugging me. Now:
Sort of closes https://github.com/bids-standard/bids-website/issues/474, which was about the opposite problem.

fix(dark): Replace DICOM reorganization figure in dark mode

---

docs/collaboration/reports/google_summer/2024-gsod.md

I think both could be improved, but these are my final drafts.

Add GSOD 2024 summary and update metrics

---

data/beps/beps.yml

Updated to add Physio BEP. Still need to add two leads as contributors to appropriate file in BIDS specification repo.

[ENH] Add BEP 045: Peripheral Physiological Recordings

---

.github/workflows/linkcheck.yml

Update link checker action URL in GHA workflow file: `gaurav-nelson/github-action-markdown-link-check` is no longer maintained, and has been superseded by
`tcort/github-action-markdown-link-check`. Documentation: https://github.com/tcort/github-action-markdown-link-check

[INFRA] Update link checkeri action URL in GHA workflow file

---

data/people/maintainers.yml
docs/collaboration/index.md

closes #660
- added important parts of the [BIDS maintainer guide](https://github.com/bids-standard/bids-specification/blob/master/Maintainers_Guide.md#why-become-a-maintainer) to the website 
- added an info box with a call for joining the BIDS maintainer team

Add parts of BIDS maintainer guide to website

---

data/beps/beps.yml

Fix layout of `status` section in BEPs 44 through 46:
- Remove the pipe operator.
- Remove excessive indentation.
- Use `status` instead of `update` for BEP044
Prior to this patch set, the `status` sections of the mentioned BEPs were not being rendered (BEP044) or were being rendered (BEP045 and BEP046) as bullet lists where each item contained a single letter from the actual words on each sentence.

STY: Fix layout of `status` section in BEPs 44 through 46

---

data/beps/beps.yml
tools/ci/validate_people.py

Down to 4 missing citations:
```
󰅂 uv run tools/ci/validate_people.py | grep '^0|NOT|no email' | grep '^ ' -B1
13-	032 Microelectrode electrophysiology
14:	      no email in specification/CITATION.cff.
15:	    NOT FOUND Andrew Davison
--
28-	045 Peripheral Physiological Recordings
29:	    NOT FOUND Mary Miedema
30:	    NOT FOUND Stefano Moia
31:	    NOT FOUND Sourav Kulkarni
```
I believe these folks are:
@apdavison @m-miedema @smoia @Sourav-Kulkarni
Also @lzehl is missing an email in the main spec CITATION.cff, but I relaxed the check to only be an error if there are no BEP leads with emails.

chore: Sync BEP information with spec CITATION.cff

---

docs/overrides/main.html

----
📚 Documentation preview 📚: https://bids-website--726.org.readthedocs.build/en/726/

Take down steering nomination banner
