index.html
=> Add Donders tools

index.html
=> Clarify how to get help

index.html
Embedded the google group
Added a space between the bids contributor guide hyperlink and 'Please adhere to our Code of Conduct'
=> Embedded google group

index.html
Just noticed that our tool with @teonbrooks was not listed on the website.
=> add mne-bids

index.html
- added the ones that were just sent around regarding "The road to BIDS Derivatives - 1st of October marks RC1"
- included the BEP number for each and ordered them
=> updated list of BEPs under "Getting Involved"

index.html
The name of this toolkit has been updated
=> Rename BIDScoiner to BIDScoin

index.html
https://neurostars.org/t/generic-fmri-data-convertor-to-bids/3171
=> * Added data2bids tool

index.html
Added two repositories we have been working on recently
(also fixed indentation error...)
=> Added software from Macquarie University

index.html
additions - 
- replaced the survey link with the results link
- added a link to a google form to input emails for occasional emails regarding BIDS
- added link to OSF: a collection of powerpoints on BIDS
=> added survey results, email input, and powerpoints

index.html
This might help with the findability of the webpage.
=> Adding Schema.org annotations

index.html
addresses point 3 of https://github.com/bids-standard/bids-specification/issues/266
=> add twitter badge

index.html
=> added feedback section and form

_config.yml, _data/navigation.yaml, _layouts/default.html, _pages/news.md, _posts/2019-10-22-voting-results.md, _posts/2019-12-14-new_website.md, _posts/2019-12-19-new_website.md, assets/css/style.scss
and made another attempt to fix the `baseurl`, such that it renders properly on localhost, on my own github repository and on the bids.neuroimaging.io.
=> create section with news 

_posts/2019-12-31-meet-the-bids-steering-group.md
=> fix typo: brin->brain

_pages/get_involved.md
=> improve visibility of bids 2.0 paragraph

_pages/getting_started.md
in the getting started section
=> add link to BIDS discussion email list

_pages/getting_started.md, _posts/2020-01-02-announcement-community-forum-events.md
closes #95 closes #99 
This PR is about adding links.
=> [DOC] Minor content updates

_posts/2020-03-12-Steering-Group-executive-summary,-action-items,-and-minutes.md
consistent with https://github.com/bids-standard/bids-website/pull/110#issuecomment-603556501
=> DOC: format the action items as table,

_pages/benefits.md
=> add bids-matlab to list. 

_posts/2020-03-30-Steering-Group-executive-summary,-action-items,-and-minutes.md
This PR captures sharing the third Steering Group meeting: executive summary, action items, and minutes
=> BIDS Steering Group meeting: executive summary, action items, minutes #3

LICENSE
=> create CC-BY 4.0 license.

_posts/2020-03-30-Steering-Group-executive-summary,-action-items,-and-minutes.md, _posts/2020-04-15-v1.3.0-release-next-focus.md
this blogpost accompanies our v1.3.0 release of the specification and sets out our next focus for the community
=> v1.3.0 release and next focus blogpost

README.md
also some text fixes to README.
preview: https://github.com/bids-standard/bids-website/blob/6e8b5c73851c47448acf58daac20ca0745526cfb/README.md
=> add logo to README

_pages/benefits.md
Dear BIDS team,
As @sappelhoff commented at Issue#124, I'm opening a pull request for adding my BIDS converter for a preclinical Bruker MRI scanner into your webpage.  Please let me know if there is anything I need to make a change to this to prevent any conflict with your standard.
=> add BrkRaw to list

_posts/2020-04-16-Steering-Group-executive-summary,-action-items,-and-minutes.md, _posts/2020-05-07-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR captures Steering Group executive summary, action items, and minutes from their meetings on: April 16 and May 7
=> Add Steering Group meeeting shareables #4 and #5

_bep_collection/bep003.md
=> make bep003 link to GH PR

_bep_collection/bep024.md
BEP24 was previously redirecting to BEP25
=> Fix BEP24 redirect

_posts/2020-05-28-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR captures Steering Group executive summary, action items, and minutes from their meeting on: May 28
=> Add Steering Group meeeting shareables

_pages/index.md
changed "ressources" to "resources"
=> typo fix on index.md

_posts/2020-06-12-BIDS-specification-v1.4.0-released.md
Press release addresses:
- announcing common derivatives with the associated common principles, metadata, and entities added
- our journey from conception to release
=> Adding v1.4.0 press release

_posts/2020-06-19-BIDS-OHBM-OSR-2020.md
Generated a list of [talks happening in the OHBM-OSR](https://github.com/ohbm/osr2020/issues?q=is%3Aissue+is%3Aopen+bids) that are related to BIDS. I took a broad approach to give a better sense of the wide range of ways BIDS can be applied throughout the field. 
There are a few talks that are yet to be scheduled - the post can be updated when they are
=> BIDS at OHBM-OSR

LICENSE
mirror https://github.com/bids-standard/bids-specification/pull/521
=> add copyright holder to license

_posts/2020-06-18-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR captures Steering Group executive summary, action items, and minutes from their meeting on: June 18
=> Steering Group meeting shareables 2020-06-18

_posts/2020-07-09-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR adds the latest (7/9) Steering Group meeting: executive summary, action items, and minutes
=> Steering Group meeting shareables 2020-07-09

_bep_collection/bep031.md, _pages/get_involved.md
for discussion, see: https://github.com/bids-standard/bids-specification/issues/510
=> BEP: add bep031

_posts/2020-07-30-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR adds the latest (7/30) Steering Group meeting: executive summary, action items, and minutes
=> Add Steering Group July 30 meeting shareables

_posts/2020-08-20-Steering-Group-executive-summary,-action-items,-and-minutes.md
sharing Steering Group executive summary, action items, and minutes from their August 20 meeting
=> Aug.20 Steering Group meeting shareable

_posts/2020-09-15-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR shares latest Steering Group meeting: executive summary, action items, minutes
=> Add Sept.15 Steering Group shareable

_bep_collection/bep009.md
as discussed in a separate slack message. cc @melanieganz
=> change redirect link for bep009

_posts/2020-10-01-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR adds the latest Steering Group meeting shareable to the website
=> Add SG meeting

_pages/index.md
PR initializes the sharing of the grant writing kit. This kit is being placed here for now - will likely need to be moved around to improve awareness of this kit. This can be done as the organizational design is implemented
=> Grant writing kit initialization

_posts/2020-10-22-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR adds the executive summary, action items, and minutes from the Steering Group meeting held on Thursday, October 22
=> Add 10-22 SG meeting

_pages/benefits.md
This PR introduces a new tool to be added under "Other Tools" section, a GUI form that generates dataset description json file
=> Add GUI dataset description generator to software list

_posts/2020-11-12-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR adds the executive summary, action items, and minutes from the Steering Group meeting held on Thursday, November 12
=> Add 11-12 SG meeting 

_posts/2020-12-03-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR adds the executive summary, action items, and minutes from the Steering Group meeting held on Thursday, December 3
=> Add 12-03 SG meeting

_posts/2021-01-14-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR adds the Steering Group executive summary, action items, and minutes from the January 14 meeting
=> Add Steering Group Jan.14 meeting

_posts/2021-02-04-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR adds the Steering Group executive summary, action items, and minutes from the February 4 meeting
=> Add Steering Group meeting - February 4

_config.yml, _redirects/starter-kit.md
closes #171 
@effigies is this what you had in mind?
=> add starter-kit redirect to bids-starter-kit

_posts/2021-03-18-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR adds the Steering Group executive summary, action items, and minutes from their March 18 meeting
=> Add 2021-03-18 Steering Group meeting

_posts/2021-02-25-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR adds the Steering Group executive summary, action items, and minutes from the February 25 meeting
=> Add 2021-02-25 Steering Group meeting

_posts/2021-04-08-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR adds the Steering Group executive summary, action items, and minutes from their April 8 meeting
=> add 2021-04-08 Steering Group meeting shareable

_posts/2021-04-29-Steering-Group-executive-summary,-action-items,-and-minutes.md
PR adds the Steering Group executive summary, action items, and minutes from their April 29 meeting
=> Add 2021-04-29 Steering Group meeting shareable

.github/check_md_links.yml
=> ci: add linkchecker

_data/maintainers.yml, _posts/2019-12-31-meet-the-bids-steering-group.md, md_link_check_config.json
@bendhouseart 
To make it official ! :smile: :tada:
=> [ENH] add anthony as maintainer

_posts/2021-09-20-BIDS-Steering-Group-Election-2021.md
PR intends to add the Steering Group election blog post to the website
=> Add Steering Group election post

_posts/2021-11-08-BIDS-Microscopy-community-review.md
PR seeks to add the community review blog post for BEP031:Microscopy
=> BEP031 community review blog post

_posts/2020-03-20-engage-with-the-bids-ecosystem.md, _posts/2020-06-12-BIDS-specification-v1.4.0-released.md, _posts/2020-06-18-Steering-Group-executive-summary,-action-items,-and-minutes.md, _posts/2020-06-19-BIDS-OHBM-OSR-2020.md, _posts/2020-06-24-Join-the-BIDS-community-on-the-BrainHack-Mattermost.md, _posts/2020-07-09-Steering-Group-executive-summary,-action-items,-and-minutes.md, _posts/2020-07-30-Steering-Group-executive-summary,-action-items,-and-minutes.md, _posts/2020-08-20-Steering-Group-executive-summary,-action-items,-and-minutes.md, _posts/2020-09-15-Steering-Group-executive-summary,-action-items,-and-minutes.md, _posts/2020-10-22-Steering-Group-executive-summary,-action-items,-and-minutes.md, _posts/2020-11-02-BIDS-ASL-community-review.md, _posts/2020-11-12-Steering-Group-executive-summary,-action-items,-and-minutes.md, _posts/2021-01-14-Steering-Group-executive-summary,-action-items,-and-minutes.md, _posts/2021-02-04-Steering-Group-executive-summary,-action-items,-and-minutes.md, _posts/2021-02-25-Steering-Group-executive-summary,-action-items,-and-minutes.md, _posts/2021-03-18-Steering-Group-executive-summary,-action-items,-and-minutes.md, _posts/2021-04-08-Steering-Group-executive-summary,-action-items,-and-minutes.md, _posts/2021-04-29-Steering-Group-executive-summary,-action-items,-and-minutes.md, _posts/2021-06-15-BIDS-Town-Hall-2021.md
using the same fix as Chris in https://github.com/bids-standard/bids-specification/pull/932#issuecomment-971703786
=> fix links and whitespace

_data/MEEG_converters.yml
=> [ENH] add eeg2bids converter

_posts/2022-06-14-BIDS-Town-Hall-2022.md
adding blog post for the bids town hall in the open science room at ohbm
=> BIDS town hall 2022 blogpost

_posts/2022-07-28-farewell-franklin.md
=> news item: farewell franklin

_config.yml, _includes/steering_group_election_section.html
to be merged when sending announcement email
=> [ENH] update and activate election banner

md_link_check_config.json
=> [FIX] update md_link_check_config.json to ignore dead links

_includes/converters_table.html, _includes/steering_group_election_section.html, _sass/custom.scss
- improve responsive design of a election banner
- improve responsive design of converter tables (closes #211)
=> [ENH] Improve responsive design

CONTRIBNUTING.md, _layouts/index.html, _pages/index.md
Figure that this may give more visibility to our social media.
Could probably to the same with our youtube channel.
=> [ENH] add twitter side bar on landing page

_sass/custom.scss
=> [ENH] style dropdown

_pages/get_started.md
following the discussion in the steering group meeting.
=> ENH - promote the validator when getting started

_data/MEEG_converters.yml, _data/converters.yml, _data/from_BIDS_converters.yml, _data/other_converters.yml, _data/physio_converters.yml
remove deprecated updated field from converter yml files
=> [MNT] remove deprecated updated field

_data/converters.yml
closes https://github.com/ColinVDB/BMAT/issues/1
=> [ENH] add BMAT converter

_pages/governance.md
related to https://github.com/bids-standard/bids-specification/issues/1316
@Remi-Gau is this what you had in mind?
=> mention place where anon elec data is stored

_data/other_converters.yml
=> [ENH] add sim2bids converter

_data/beps.yml, _data/beps_completed.yml, _includes/beps_completed_table.html, _includes/beps_table.html, _pages/get_involved.md, _sass/custom.scss
preview: https://deploy-preview-271--astounding-beignet-8ca2d6.netlify.app/get_involved.html#extending-the-bids-specification
- switch blocking point column for content column
- render completed beps from yml
=> [ENH] improve BEP tables 

_pages/bep_guide.md
as per the steering group discussion 19 January 2023
=> added info about DICOM

.vscode/settings.json, _pages/benefits.md
closes #275 
preview https://deploy-preview-277--astounding-beignet-8ca2d6.netlify.app/benefits.html#other-tools
- also removes some tools that are in fact BIDS apps and are already listed on the bids app website
=> [ENH] add extra BIDS tools

_data/MEEG_converters.yml, _includes/beps_completed_table.html, _includes/beps_table.html, _includes/converters_table.html
preview: https://deploy-preview-276--astounding-beignet-8ca2d6.netlify.app/benefits.html#eeg-meg-ieeg-converters
closes #268
=> [ENH] point to converters doc rather than repo

_data/beps_completed.yml
=> [FIX] add bep 008 and fix bep 009 name

_bep_collection/bep040.md, _data/beps.yml
@sdiebolt and @tdeffieux please comment with the GitHub handles of the other leads of this BEP and have a quick look at the changed files, whether all these additions seem sensible to you.
=> add BEP040 -- fUS

.github/dependabot.yml, .github/workflows/bep_update_reminder.yml
=> Add BEP update reminder

_data/beps.yml, _pages/get_involved.md
=> [FIX] move bep 13 to "other BEP" table

_posts/2020-06-24-Join-the-BIDS-community-on-the-BrainHack-Mattermost.md, md_link_check_config.json
- some are just false positive (twitter is not down... yet)
- some links ARE dead and my google fu is not good enough to find where the thing was moved (see #300)
=> [FIX] Ignore some dead links

.vscode/settings.json, _posts/2021-05-20-Steering-Group-minutes.md, _posts/2021-06-10-Steering-Group-minutes.md, _posts/2021-07-01-Steering-Group-minutes.md, _posts/2021-08-12-Steering-Group-minutes.md, _posts/2021-09-02-Steering-Group-minutes.md, _posts/2021-11-04-Steering-Group-minutes.md, _posts/2021-12-14-Steering-Group-minutes.md, templates/YYYY-MM-DD-Steering-Group-minutes.md, tools/Makefile, tools/convert_to_md.py, tools/convert_to_md.sh, tools/requirements.txt
relates to #294 
new pages 
- https://deploy-preview-302--astounding-beignet-8ca2d6.netlify.app/2021/05/20/steering-group-minutes
- https://deploy-preview-302--astounding-beignet-8ca2d6.netlify.app/2021/06/10/steering-group-minutes
- https://deploy-preview-302--astounding-beignet-8ca2d6.netlify.app/2021/07/01/steering-group-minutes
- https://deploy-preview-302--astounding-beignet-8ca2d6.netlify.app/2021/08/12/steering-group-minutes
- https://deploy-preview-302--astounding-beignet-8ca2d6.netlify.app/2021/09/02/steering-group-minutes
- https://deploy-preview-302--astounding-beignet-8ca2d6.netlify.app/2021/11/04/steering-group-minutes
- https://deploy-preview-302--astounding-beignet-8ca2d6.netlify.app/2021/12/14/steering-group-minutes
=> [ENH] add steering group minutes 2021

_pages/get_involved.md, _pages/get_started.md, _pages/index.md
fixes #306 
@Remi-Gau let me know if this also fixes #291.
Also, this needs approving reviews by some, to make sure that everybody is on board with my suggestion: https://github.com/bids-standard/bids-website/issues/306#issue-1732393543
=> Make communication channels more obvious

_pages/benefits.md, md_link_check_config.json
closes #312 
closes #314
fixes #316
=> [ENH] update tools

_data/beps.yml, _pages/get_involved.md
- closes #236 
See https://github.com/bids-standard/bids-website/issues/236#issuecomment-1647697737 for information and context.
=> move BEP025 to new section

_data/maintainers.yml
following:
- https://github.com/bids-standard/bids-specification/pull/1571
=> add Kimberly Ray to maintainers

_data/converters.yml
=> [ENH] add niix2bids

_layouts/index.html
=> [FIX] remove twitter banner

_data/converters.yml, _data/tools.yml, _includes/list_tools.html, _pages/benefits.md
- relates to #331 
- closes #330
=> [ENH] organize list of tools

_posts/2023-05-25-Steering-Group-minutes.md, _posts/2023-06-15-Steering-Group-minutes.md, _posts/2023-07-06-Steering-Group-minutes.md, _posts/2023-07-27-Steering-Group-minutes.md, _posts/2023-08-17-Steering-Group-minutes.md, _posts/2023-09-07-Steering-Group-minutes.md, tools/Makefile, tools/README.md, tools/convert_to_md.py, tools/convert_to_md.sh
cc @Remi-Gau I also wrote a bit of documentation, feel free to check. Thanks for establishing this machinery!
=> add meeting notes and DOC

_pages/index.md
I made some small edits on the `index.md` home page to make it more up to date.
=> [ENH] home page updates

_pages/acknowledgments.md
Ceremony should happen 30th, money to flow at some point I guess.
=> Add recently received (to be yet accepted physically) prize into Acknowldgements

_pages/governance.md
This addition was adopted by the BIDS community in the 2023 election.
=> Add Appendix H: Governance amendment procedure

_layouts/index.html, _pages/index.md
- in landing page
- in footer (no icon for now)
=> [ENH] update social media

.gitignore, .pre-commit-config.yaml, LICENSE, _layouts/default.html, _layouts/index.html, _pages/governance.md, _pages/index.md, _posts/2022-10-29-BIDS-Version-1.8.0-Release.md, _posts/2023-07-06-Steering-Group-minutes.md, md_link_check_config.json, pyproject.toml, tools/README.md, tools/bep_gantt_html_create.py, tools/bep_gantt_mermaid_insert.py
cc @Remi-Gau 
will add more commits to add some documentation in the `tools/README.md`.
We should also update the BIDS spec release protocol, so that upon a release, the `timeline.csv` and `beps_completed.yml` files are updated 🤔
=> Gantt chart: misc fixes and documentation 

_pages/governance.md
=> Governance: Remove mention to specific social media channels

_posts/2023-08-17-Steering-Group-minutes.md, _posts/2023-09-28-Steering-Group-minutes.md, _posts/2023-10-19-Steering-Group-minutes.md, _posts/2023-11-09-Steering-Group-minutes.md, _posts/2023-11-30-Steering-Group-minutes.md, tools/convert_to_md.py
Should have been added sooner, but better late than never.
=> Steering Group meeting notes -- old updates from 2023

_posts/2024-01-11-Steering-Group-minutes.md, _posts/2024-02-01-Steering-Group-minutes.md, _posts/2024-02-22-Steering-Group-minutes.md, tools/convert_to_md.py, tools/convert_to_md.sh
adding the notes for the public to see
=> SG 2024 updates

_data/maintainers.yml, _includes/members_table.html
resolves #371 
let's see if this works
=> add photo CR

_posts/2024-03-29-BIDS_Community_Survey_2024_closing.md
Another notice to remind folks to respond to the survey.
=> Add the survey closing reminder

_data/tools.yml
=> [ENH] add psychopy-bids

_data/MEEG_converters.yml, _data/converters.yml, _data/other_converters.yml, _pages/benefits.md
fixed some broken links and added some small formatting fixes.
=> link and format edits

_bep_collection/bep042.md, _bep_collection/bep043.md, _data/beps.yml
cc @neuromechanist @ericearl 
Please review the entries for accuracy.
=> BEPs: Assign numbers 42 and 43 to EMG and Term Mapping

_data/beps.yml
- closes https://github.com/bids-standard/bep021/issues/10
=> Reduce number of moderators on BEP021

.gitignore, docs/contact.md, docs/index.md, docs/stylesheets/extra.css, docs/tools/index.md, docs/tools/validator.md
Added gisus to several pages and updated navigation/tocs to simplify some pages.
=> Add Giscus plus minor formatting tweaks

faq/mri/convert-nifti.question.md
the question was in the general section and not the MRI section
note that this is one of the most frequently asked question on neurostars so we should probably work on improving the answer
=> [FIX] move question conversion nifti

.github/workflows/check_md_links.yml, .github/workflows/validation.yml, docs/getting_started/folders_and_files/derivatives.md, docs/getting_started/folders_and_files/files.md, docs/getting_started/folders_and_files/folders.md, docs/getting_started/folders_and_files/index.md, docs/getting_started/folders_and_files/metadata.md, docs/getting_started/resources/dependencies.md, docs/getting_started/resources/glossary.md, docs/getting_started/resources/links.md, docs/getting_started/resources/publications.md, docs/getting_started/resources/talks.md, docs/index.md, mkdocs.yml
I believe that all menu items under "Getting started" in the new navigation now have their corresponding page.
=> [ENH] added md files from bids-starter-kit repository

docs/bep/beps.md, docs/contact.md, docs/datasets/index.md, docs/impact.md, docs/index.md, docs/tools/apps/index.md, docs/tools/converters/meeg.md, docs/tools/converters/mri-pet.md, docs/tools/converters/others.md, docs/tools/converters/physio.md, docs/tools/others.md, docs/tools/validator.md, mkdocs.yml
- closes #451 
- do not hide the navigation bar (on the left) and the table of content bar (on the right) on any page
- integrate TOC in navigation
=> [ENH] improve navigation

_bep_collection/bep044.md, _data/beps.yml
Attn @neuromechanist  @dorahermes @VisLab @smakeig
=> Assign BEP044 to "Stimuli BEP"

data/beps/beps.yml
=> [ENH] add bep 44

docs/collaboration/index.md, docs/getting_started/index.md, docs/standards/bids_app_specification/contributors.md, docs/standards/index.md
Added text to all sections that were listed to be done ASAP. 
Closes #461
=> intro sections added

data/people/advisory.yml
=> [ENH] add leads BEP22 to BIDS advisory group

.gitmodules, docs/collaboration/contributors.md, mkdocs.yml
=> [ENH] add contributing and COC from .github repo

docs/extensions/beps.md, docs/getting_started/templates/index.md, docs/impact/index.md, makefile, mkdocs.yml, templates/README.md, templates/dataset_description.json, templates/yyyy-mm-dd-steering-group-minutes.md, tools/README.md
=> [ENH] add some templates from the BIDS starter kit

_config.yml, _includes/steering_group_election_section.html
=> [Old Website] update banner for steering group election 2024

docs/datasets/index.md
Updated database page to more clearly link to a sample of locations where users can find BIDS datasets. 
Also updated and made text for each section a bit more clear.
=> Database info update

docs/getting_started/folders_and_files/folders.md
Hi, I found an error during reading, so here's a fix.
Thanks for your efforts!
=> fixed description of mrs data type

data/tools/converters.yml
Hi there,
This PR proposes to update the list of converters proposed by Clinica.
=> Update list of converters for Clinica

data/tools/apps.yml, docs/datasets/index.md, docs/overrides/main.html
Follow up to the issue #560 . Updated the information of the hippunfold and micapipe apps.
=> [ENH] Update hippunfold and micapipe apps info

docs/impact/index.md
Reordered impact page per meeting notes. 
Expanded on much of the history and section text. 
Draft for review. More info need to be filled in, but looking for review of what is done now. 
- this addresses #486
=> updating BIDS impact page

docs/contact/index.md
=> [ENH] Add steering email

docs/collaboration/reports/google_summer/2018-gsoc.md, docs/collaboration/reports/google_summer/2024-gsod.md, docs/getting_started/folders_and_files/metadata/json.md, md_link_check_config.json
- use markdown for some table
- fix links
=> [STY] fix some styling issues in the reports

mkdocs.yml
=> [FIX] update mkdocs.yml to fix navbar

data/people/past_steering.yml, data/people/steering.yml
=> [ENH] update steering group

data/tools/tools.yml
Follow-up on: https://github.com/bids-standard/bids-website/pull/606
Should now have the main branch as base.
=> Add lazybids and lazybids-ui to tools.yml

data/tools/apps.yml
Hello
I would like ln2t/cvrmap to be listed on the BIDS app repo.
Let me know if you intended such request to be handled differently, I guessed I should directly submit a PR but I might be wrong!
Regards
AR
=> added CVRmap

.readthedocs.yaml
Should shave about a minute off of RTD builds.
=> chore(rtd): Build environment with uv

data/beps/beps.yml
With @satra, we would like to add @yarikoptic in the BIDS-Prov BEP leads.
=> Update BIDS-Prov BEP leads

data/beps/beps.yml
Providing a small update to the BEP036 section.
=> Update data/beps/beps.yml for BEP036

data/beps/beps.yml
=> Add Tractography BEP

docs/blog/posts/2025-07-03-bids-town-hall.md
Blog post for BIDS Town Hall 2025.
=> Add 2025-07-03-bids-town-hall.md
